config/routes.rb
Rails.application.routes.draw do
  get 'spells/get_spell' => 'spells#get_spell'
  resources :campaigns do
    get 'show_campaign', on: :member
    get 'edit_campaign', on: :member
    get 'new_campaign', on: :collection
    post 'user_create', on: :collection
  end
  resources :encounters do
    get 'show_encounter', on: :member
    get 'edit_encounter', on: :member
    get 'new_encounter', on: :collection
    post 'user_create', on: :collection
  end

  resources :creatures
  resources :spells
  resources :users
  resources :user_sessions

  root to: 'static#home'

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  get '/:page' => 'static#show'
end

app/models/creature.rb
class Creature < ActiveRecord::Base
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :set_creature, only: [:show, :edit, :update, :destroy]

  def index
    @creatures = Creature.all
  end

  def show
  end

  def new
    @creature = Creature.new
  end

  def edit
  end

  def create
    @creature = Creature.new(creature_params)
    if @creature.save
      redirect_to @creature, notice: 'Creature was successfully created.'
    else
      render :new
    end
  end

  def update
    if @creature.update(creature_params)
      redirect_to @creature, notice: 'Creature was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @creature.destroy
    redirect_to creatures_url, notice: 'Creature was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creature
      @creature = Creature.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creature_params
      params.require(:creature).permit(:name, :armor_class, :hitpoints, :speed, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :saving_throw, :damage_immunities, :condition_immunities, :senses, :languages, :challenge_rating, :experience, :description)
    end
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/views/creatures/_form.html.haml
= form_for @creature do |f|
  - if @creature.errors.any?
    #error_explanation
      %h2= "#{pluralize(@creature.errors.count, "error")} prohibited this creature from being saved:"
      %ul
        - @creature.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :armor_class
    = f.number_field :armor_class
  .field
    = f.label :hitpoints
    = f.number_field :hitpoints
  .field
    = f.label :speed
    = f.number_field :speed
  .field
    = f.label :strength
    = f.number_field :strength
  .field
    = f.label :dexterity
    = f.number_field :dexterity
  .field
    = f.label :constitution
    = f.number_field :constitution
  .field
    = f.label :intelligence
    = f.number_field :intelligence
  .field
    = f.label :wisdom
    = f.number_field :wisdom
  .field
    = f.label :charisma
    = f.number_field :charisma
  .field
    = f.label :saving_throw
    = f.text_field :saving_throw
  .field
    = f.label :damage_immunities
    = f.text_field :damage_immunities
  .field
    = f.label :condition_immunities
    = f.text_field :condition_immunities
  .field
    = f.label :senses
    = f.text_field :senses
  .field
    = f.label :languages
    = f.text_field :languages
  .field
    = f.label :challenge_rating
    = f.text_field :challenge_rating
  .field
    = f.label :experience
    = f.number_field :experience
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/creatures/edit.html.haml
%h1 Editing creature

= render 'form'

= link_to 'Show', @creature
\|
= link_to 'Back', creatures_path

app/views/creatures/index.html.haml
%h1 Listing creatures

%table
  %thead
    %tr
      %th Name
      %th Armor class
      %th Hitpoints
      %th Speed
      %th Strength
      %th Dexterity
      %th Constitution
      %th Intelligence
      %th Wisdom
      %th Charisma
      %th Saving throw
      %th Damage immunities
      %th Condition immunities
      %th Senses
      %th Languages
      %th Challenge rating
      %th Experience
      %th Description
      %th
      %th
      %th

  %tbody
    - @creatures.each do |creature|
      %tr
        %td= creature.name
        %td= creature.armor_class
        %td= creature.hitpoints
        %td= creature.speed
        %td= creature.strength
        %td= creature.dexterity
        %td= creature.constitution
        %td= creature.intelligence
        %td= creature.wisdom
        %td= creature.charisma
        %td= creature.saving_throw
        %td= creature.damage_immunities
        %td= creature.condition_immunities
        %td= creature.senses
        %td= creature.languages
        %td= creature.challenge_rating
        %td= creature.experience
        %td= creature.description
        %td= link_to 'Show', creature
        %td= link_to 'Edit', edit_creature_path(creature)
        %td= link_to 'Destroy', creature, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Creature', new_creature_path

app/views/creatures/new.html.haml
%h1 New creature

= render 'form'

= link_to 'Back', creatures_path

app/views/creatures/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @creature.name
%p
  %b Armor class:
  = @creature.armor_class
%p
  %b Hitpoints:
  = @creature.hitpoints
%p
  %b Speed:
  = @creature.speed
%p
  %b Strength:
  = @creature.strength
%p
  %b Dexterity:
  = @creature.dexterity
%p
  %b Constitution:
  = @creature.constitution
%p
  %b Intelligence:
  = @creature.intelligence
%p
  %b Wisdom:
  = @creature.wisdom
%p
  %b Charisma:
  = @creature.charisma
%p
  %b Saving throw:
  = @creature.saving_throw
%p
  %b Damage immunities:
  = @creature.damage_immunities
%p
  %b Condition immunities:
  = @creature.condition_immunities
%p
  %b Senses:
  = @creature.senses
%p
  %b Languages:
  = @creature.languages
%p
  %b Challenge rating:
  = @creature.challenge_rating
%p
  %b Experience:
  = @creature.experience
%p
  %b Description:
  = @creature.description

= link_to 'Edit', edit_creature_path(@creature)
\|
= link_to 'Back', creatures_path