config/routes.rb
Rails.application.routes.draw do
  get 'spells/get_spell' => 'spells#get_spell'
  resources :campaigns do
    get 'show_campaign', on: :member
    get 'edit_campaign', on: :member
    get 'new_campaign', on: :collection
    post 'user_create', on: :collection
  end
  resources :encounters do
    get 'show_encounter', on: :member
    get 'edit_encounter', on: :member
    get 'new_encounter', on: :collection
    post 'user_create', on: :collection
  end

  resources :creatures
  resources :spells
  resources :users
  resources :user_sessions

  root to: 'static#home'

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  get '/:page' => 'static#show'
end

app/models/encounter.rb
class Encounter < ActiveRecord::Base
  belongs_to :campaign
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  before_action :set_encounter, only: [:show, :edit, :update, :destroy, :edit_encounter, :show_encounter]

  def index
    @encounters = Encounter.all
  end

  def show
  end

  def show_encounter
  end

  def new
    @encounter = Encounter.new
  end

  def new_encounter
    @encounter = Encounter.new
  end

  def edit
  end

  def edit_encounter
  end

  def create
    @encounter = Encounter.new(encounter_params)
    if @encounter.save
      redirect_to @encounter, notice: 'Encounter was successfully created.'
    else
      render :new
    end
  end

  def user_create
    @encounter = Encounter.new(encounter_params)

    if @encounter.save
      redirect_to show_encounter_encounter_path(@encounter), notice: 'Encounter was successfully created.'
    else
      render :new
    end
  end

  def update
    if @encounter.update(encounter_params)
      redirect_to show_encounter_encounter_path(@encounter), notice: 'Encounter was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @encounter.destroy
    redirect_to encounters_url, notice: 'Encounter was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encounter
      @encounter = Encounter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encounter_params
      params.require(:encounter).permit(:campaign_id, :name)
    end
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/views/encounters/_form.html.haml
= form_for @encounter do |f|
  - if @encounter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@encounter.errors.count, "error")} prohibited this encounter from being saved:"
      %ul
        - @encounter.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :campaign_id
    = f.number_field :campaign_id
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/encounters/edit.html.haml
%h1 Editing encounter

= render 'form'

= link_to 'Show', @encounter
\|
= link_to 'Back', encounters_path

app/views/encounters/edit_encounter.html.haml
%h1
  Editing
  =@encounter.name

= form_for @encounter do |f|
  - if @encounter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@encounter.errors.count, "error")} prohibited this encounter from being saved:"
      %ul
        - @encounter.errors.full_messages.each do |msg|
          %li= msg
  .edit-fieldset
    .field
      = f.label :name
      = f.text_field :name
  .actions
    = f.submit 'Save', {:class=>"button"}
    = link_to 'Back', show_encounter_encounter_path(@encounter), {:class=>"button"}

app/views/encounters/index.html.haml
%h1 Listing encounters

%table
  %thead
    %tr
      %th Campaign
      %th Name
      %th
      %th
      %th

  %tbody
    - @encounters.each do |encounter|
      %tr
        %td= encounter.campaign_id
        %td= encounter.name
        %td= link_to 'Show', encounter
        %td= link_to 'Edit', edit_encounter_path(encounter)
        %td= link_to 'Destroy', encounter, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Encounter', new_encounter_path

app/views/encounters/new.html.haml
%h1 New encounter

= render 'form'

= link_to 'Back', encounters_path

app/views/encounters/new_encounter.html.haml
%h1 New encounter

= form_for @encounter, url: 'user_create' do |f|
  - if @encounter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@encounter.errors.count, "error")} prohibited this encounter from being saved:"
      %ul
        - @encounter.errors.full_messages.each do |msg|
          %li= msg
  .edit-fieldset
    .field
      = f.label :campaign_id
      = f.select(:campaign_id) do
        - current_user.campaigns.each do |c|
          %option{:value => c.id}= c.name
    .field
      = f.label :name
      = f.text_field :name
  .actions
    = f.submit 'Save', {:class=>"button"}

app/views/encounters/show.html.haml
%p#notice= notice

%p
  %b Campaign:
  = @encounter.campaign_id
%p
  %b Name:
  = @encounter.name

= link_to 'Edit', edit_encounter_path(@encounter)
\|
= link_to 'Back', encounters_path

app/views/encounters/show_encounter.html.haml
%input#page-info{type: 'hidden', value: 'show_encounter'}

%p#notice= notice

#encounterHeading
  %h2
    = @encounter.name
    = link_to(edit_encounter_encounter_path(@encounter)) do
      %i.fa.fa-pencil
  in campaign
  %select.campaign-name
    - current_user.campaigns.each do |c|
      %option{:value => c.id}= c.name

#encounter-creatures-table.table
  #add-monster-button
    %i.fa.fa-plus-circle.fa-2x
  .tr
    #monster1.monster-row
      .name
        %input{name: "encounter-name", value: "Grum - (Goblin 1)", type: "text/plain", size: 12}
      .attributes
        .health-info-wrapper
          %label.max-HP-label HP:
          %input.current-HP{type:'number', name:'hp', min:'0', max:'999', value:'30'}
          %hr
          %label.max-HP-label Max HP:
          %input.max-HP{type:'number', name:'hp', min:'0', max:'999', value:'30'}
        .attribute-set-wrapper
          %div.attribute
            %label AC:
            %input{type:'number', name:'hp', min:'0', max:'99', value:'12'}
          %div.attribute
            %label Init:
            %input{type:'number', name:'hp', min:'0', max:'99', value:'6'}
      %br
      %div#fieldset-wrapper
        %fieldset.attacks
          %legend
            Attacks
            .add-button
              %i.fa.fa-plus-circle.fa-lg
            .remove-button
              %i.fa.fa-minus-circle.fa-lg
          %table
            %tr
              %th Name
              %th ATK Bonus
              %th Damage/Type
              %th &nbsp
            %tr.attack-row{description:'Weight: 6lbs Properties: Heavy, two-handed'}
              %td
                Dagger
              %td
                %input.attack-bonus{type:'text', id:'attack1_attack_bonus', value:'+5'}
              %td
                %input.attack-damage{type:'text', id:'attack1_damage', value:'2d6 slashing'}
              %td.delete
                %i.fa.fa-minus-circle
                Delete
        %fieldset.spells
          %legend
            Spells
            .add-button
              %i.fa.fa-plus-circle.fa-lg
            .remove-button
              %i.fa.fa-minus-circle.fa-lg
        %fieldset.other
          %legend
            Other
          Notes:
          %textarea{cols: "26", rows: "5"}


= render 'static/creature_search'