config/routes.rb
Rails.application.routes.draw do
  get 'spells/get_spell' => 'spells#get_spell'
  resources :campaigns do
    get 'show_campaign', on: :member
    get 'edit_campaign', on: :member
    get 'new_campaign', on: :collection
    post 'user_create', on: :collection
  end
  resources :encounters do
    get 'show_encounter', on: :member
    get 'edit_encounter', on: :member
    get 'new_encounter', on: :collection
    post 'user_create', on: :collection
  end

  resources :creatures
  resources :spells
  resources :users
  resources :user_sessions

  root to: 'static#home'

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  get '/:page' => 'static#show'
end

app/models/spell.rb
class Spell < ActiveRecord::Base
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: [:show, :edit, :update, :destroy]

  def index
    @spells = Spell.all
  end

  def show
  end

  def new
    @spell = Spell.new
  end

  def edit
  end

  def create
    @spell = Spell.new(spell_params)
    if @spell.save
      redirect_to @spell, notice: 'Spell was successfully created.'
    else
      render :new
    end
  end

  def update
    if @spell.update(spell_params)
      redirect_to @spell, notice: 'Spell was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @spell.destroy
    redirect_to spells_url, notice: 'Spell was successfully destroyed.'
  end

  def get_spell
    s = Spell.find(params[:spell_id])
    spell_info = {
      spellName: s.name,
      spellCastingTime: s.casting_time,
      spellRange: s.range,
      spellComponents: s.components,
      spellDuration: s.duration,
      spellMaterialComponents: s.material_components,
      spellDescription: s.description,
      spellClass: s.spell_class,
      spellSchool: s.school,
      spellLevel: s.level,
      concentration: s.concentration,
      ritual: s.ritual
    }.to_json
    puts spell_info
    render text: spell_info
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spell
      @spell = Spell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spell_params
      params.require(:spell).permit(:name, :description, :spell_class, :level, :school, :ritual, :casting_time, :components, :concentration, :source)
    end
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/spells/_form.html.haml
= form_for @spell do |f|
  - if @spell.errors.any?
    #error_explanation
      %h2= "#{pluralize(@spell.errors.count, "error")} prohibited this spell from being saved:"
      %ul
        - @spell.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :spell_class
    = f.text_field :spell_class
  .field
    = f.label :level
    = f.number_field :level
  .field
    = f.label :school
    = f.text_field :school
  .field
    = f.label :ritual
    = f.check_box :ritual
  .field
    = f.label :casting_time
    = f.text_field :casting_time
  .field
    = f.label :components
    = f.text_field :components
  .field
    = f.label :concentration
    = f.check_box :concentration
  .field
    = f.label :source
    = f.text_field :source
  .actions
    = f.submit 'Save'

app/views/spells/edit.html.haml
%h1 Editing spell

= render 'form'

= link_to 'Show', @spell
\|
= link_to 'Back', spells_path

app/views/spells/index.html.haml
%h1 Listing spells

%table
  %thead
    %tr
      %th Name
      %th Description
      %th Spell class
      %th Level
      %th School
      %th Ritual
      %th Casting time
      %th Components
      %th Concentration
      %th Source
      %th
      %th
      %th

  %tbody
    - @spells.each do |spell|
      %tr
        %td= spell.name
        %td= spell.description
        %td= spell.spell_class
        %td= spell.level
        %td= spell.school
        %td= spell.ritual
        %td= spell.casting_time
        %td= spell.components
        %td= spell.concentration
        %td= spell.source
        %td= link_to 'Show', spell
        %td= link_to 'Edit', edit_spell_path(spell)
        %td= link_to 'Destroy', spell, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Spell', new_spell_path

app/views/spells/new.html.haml
%h1 New spell

= render 'form'

= link_to 'Back', spells_path

app/views/spells/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @spell.name
%p
  %b Description:
  = @spell.description
%p
  %b Spell class:
  = @spell.spell_class
%p
  %b Level:
  = @spell.level
%p
  %b School:
  = @spell.school
%p
  %b Ritual:
  = @spell.ritual
%p
  %b Casting time:
  = @spell.casting_time
%p
  %b Components:
  = @spell.components
%p
  %b Concentration:
  = @spell.concentration
%p
  %b Source:
  = @spell.source

= link_to 'Edit', edit_spell_path(@spell)
\|
= link_to 'Back', spells_path