config/routes.rb
Rails.application.routes.draw do
  get 'spells/get_spell' => 'spells#get_spell'
  resources :campaigns do
    get 'show_campaign', on: :member
    get 'edit_campaign', on: :member
    get 'new_campaign', on: :collection
    post 'user_create', on: :collection
  end
  resources :encounters do
    get 'show_encounter', on: :member
    get 'edit_encounter', on: :member
    get 'new_encounter', on: :collection
    post 'user_create', on: :collection
  end

  resources :creatures
  resources :spells
  resources :users
  resources :user_sessions

  root to: 'static#home'

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  get '/:page' => 'static#show'
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  has_many :encounters
  belongs_to :user
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy, :edit_campaign, :show_campaign]

  def index
    @campaigns = Campaign.all
  end

  def show
  end

  def show_campaign
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  def edit
  end

  def create
    @campaign = Campaign.new(campaign_params)
    if @campaign.save
      redirect_to @campaign, notice: 'Campaign was successfully created.'
    else
      render :new
    end
  end

  def user_create
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id

    if @campaign.save
      redirect_to show_campaign_campaign_path(@campaign), notice: 'Campaign was successfully created.'
    else
      render :new
    end
  end

  def new_campaign
    @campaign = Campaign.new
  end

  def update
    if @campaign.update(campaign_params)
      redirect_to show_campaign_campaign_path(@campaign), notice: 'Campaign was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:user_id, :name)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.haml
= form_for @campaign do |f|
  - if @campaign.errors.any?
    #error_explanation
      %h2= "#{pluralize(@campaign.errors.count, "error")} prohibited this campaign from being saved:"
      %ul
        - @campaign.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/campaigns/edit.html.haml
%h1 Editing campaign

= render 'form'

= link_to 'Show', @campaign
\|
= link_to 'Back', campaigns_path

app/views/campaigns/edit_campaign.html.haml
%h1
  Editing
  = @campaign.name

= form_for @campaign do |f|
  - if @campaign.errors.any?
    #error_explanation
      %h2= "#{pluralize(@campaign.errors.count, "error")} prohibited this campaign from being saved:"
      %ul
        - @campaign.errors.full_messages.each do |msg|
          %li= msg
  .edit-fieldset
    .field
      = f.label :name
      = f.text_field :name
  .actions
    = f.submit 'Save', {:class=>"button"}
    = link_to 'Back', show_campaign_campaign_path(@campaign), {:class=>"button"}

app/views/campaigns/index.html.haml
%h1 Listing campaigns

%table
  %thead
    %tr
      %th User
      %th Name
      %th
      %th
      %th

  %tbody
    - @campaigns.each do |campaign|
      %tr
        %td= campaign.user_id
        %td= campaign.name
        %td= link_to 'Show', campaign
        %td= link_to 'Edit', edit_campaign_path(campaign)
        %td= link_to 'Destroy', campaign, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Campaign', new_campaign_path

app/views/campaigns/new.html.haml
%h1 New campaign

= render 'form'

= link_to 'Back', campaigns_path

app/views/campaigns/new_campaign.html.haml
%h1 New campaign

= form_for @campaign, url: 'user_create' do |f|
  - if @campaign.errors.any?
    #error_explanation
      %h2= "#{pluralize(@campaign.errors.count, "error")} prohibited this campaign from being saved:"
      %ul
        - @campaign.errors.full_messages.each do |msg|
          %li= msg

  .edit-fieldset
    .field
      = f.label :name
      = f.text_field :name
  .actions
    = f.submit 'Save', {:class=>"button"}

app/views/campaigns/show.html.haml
%p#notice= notice

%p
  %b User:
  = @campaign.user_id
%p
  %b Name:
  = @campaign.name

= link_to 'Edit', edit_campaign_path(@campaign)
\|
= link_to 'Back', campaigns_path

app/views/campaigns/show_campaign.html.haml
%p#notice= notice

%h2
  = @campaign.name
  = link_to(edit_campaign_campaign_path(@campaign)) do
    %i.fa.fa-pencil

#summaryTable.table
  .table
    .tr
      .th Encounter
      .th # of Monsters
      .th Last Modified

    - @campaign.encounters.each do |enc|
      -# TODO: link to better page
      =link_to show_encounter_encounter_path(enc), {class: 'tr'} do
        .td= enc.name
        -#.td= enc.creatures.length
        .td 0
        .td= enc.updated_at

= link_to(new_encounter_encounters_path) do
  .button-table-background
    %i.fa.fa-plus-circle.fa-lg
    Encounter